spring.datasource.url=jdbc:postgresql://YOUR-HOST:5432/YOUR-DATABASE
spring.datasource.username=YOUR-USERNAME
spring.datasource.password=YOUR-PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=updateialect