spring.datasource.url=jdbc:postgresql://dpg-d7srob1kh4rs739b3lfg-a/talentmatch_db_b873
spring.datasource.username=talentmatch_db_b873_user
spring.datasource.password=vIjYU1bofh4Mptv1PArBW3u3LFpzb2N9

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update